### ISSUE TITLE
An error occurred on the MAC

### ISSUE THREAD

**Issue by weichangdong** [rfyiamcool/rocks_queue#2]
`# rocks_queue/rocks
rocks/db.go:49:10: undefined: NewHashElement
rocks/db.go:53:10: undefined: NewSortedSetElement
`
是因为没有执行下面这一步么?
`run brew tap homebrew/versions; brew install gcc48 --use-llvm to install gcc 4.8 (or higher).`

**Comment by weichangdong** [comment]
装了gcc6 报错依然.

**Comment by rfyiamcool** [comment]
你这个问题应该是没有装rocksdb....

**Comment by weichangdong** [comment]
brew  list|grep  rocksdb
rocksdb
已经装了,也重新装了,但是对rocksdb不熟,不知道怎么验证.

**Comment by theburn** [comment]
我也是类似的问题，我是linux，rocksdb是5.11.3 我用https://github.com/twmht/python-rocksdb 这个已经可以运行成功，但是 go run main.go 的时候，也是依然报错
```bash
go build
# github.com/rfyiamcool/rocks_queue/rocks
rocks/db.go:49: undefined: NewHashElement
rocks/db.go:53: undefined: NewSortedSetElement
```

**Comment by leehistory** [comment]
NewHashElement
NewSortedSetElement
同错
mac brew环境
